before_install:
  - openssl aes-256-cbc -K $encrypted_671dc0cb2713_key -iv $encrypted_671dc0cb2713_iv -in id_rsa.enc -out id_rsa -d
  - chmod 400 id_rsa
language: go
go:
  - 1.8
install: go get -v github.com/spf13/hugo
script: hugo
notifications:
  email:
    recipients:
      - c.oelmueller@gmail.com
      - anja@anjeve.de
    on_success: always
    on_failure: always
after_success:
  - rsync -av -n --delete -e "ssh -o StrictHostKeyChecking=no -l 46.38.249.61 -i id_rsa" public/ 46.38.249.61:httpdocs/kubotan/
  - rm -f id_rsa
