language: go
go:
  - 1.8
install: go get -v github.com/spf13/hugo
script: hugo
notifications:
  email:
    recipients:
      - c.oelmueller@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
after_deploy:
  - rm -f id_rsa
