before_install:
  - openssl aes-256-cbc -K $encrypted_70595de6f621_key -iv $encrypted_70595de6f621_iv -in id_rsa.enc -out id_rsa -d
  - chmod 400 id_rsa
language: go
go:
  - 1.5
install: go get -v github.com/spf13/hugo
script: hugo
notifications:
  email:
    recipients:
      - c.oelmueller@gmail.com
    on_success: always
    on_failure: always
after_success:
  - rsync -av --delete -e "ssh -o StrictHostKeyChecking=no -l kubotan-berlin.de -i id_rsa" public/ ssh.strato.de:kubotan/
  - rm -f id_rsa
